### ISSUE TITLE
Errors in homer for text data

### ISSUE THREAD

**Issue by hgweon** [rivolli/utiml#1]
Hi, 

I am trying to use the homer function but keep getting errors especially when using the predict function. I tried 10-fold cross validation on two data sets medical.arff and enron.arff. My guess is the errors come from the sparse labels in the training data. Could you please check the issue and fix it? Thanks!

**Comment by rivolli** [comment]
Hi hgweon, thank you for your report. In fact, there was 2 erros:

1. The medical problem is because there were few positive instances in some labels and it was breaking the code.
2. The enron problem was in the prediction method as you told and I fixed them basically using, drop=FALSE in some places.

I run a 10-fold cross validation using different seeds and now it is not breaking the code anymore.
I'll perform more extensive tests soon, to guarantee that the algorithm is working as it really should. But if you suspect that some results are very divergent from expected, please tell me.

Thank you again.
Best

**Comment by rivolli** [comment]
I forgot to say, but you will need to refresh your installation using: devtools::install_github("rivolli/utiml")
