### ISSUE TITLE
probabilities -> bipartition

### ISSUE THREAD

**Issue by SedaArat** [rivolli/utiml#3]
Hi there,

First off, thanks for the package, it is extremely helpful for my project.
Second, it is not an issue message. I have a question about predict function. 

I am using br model with random forest and an generating 2 outputs from predict function. One with probability = TRUE and one with probability = FALSE. How are the probabilities (when probability = TRUE) converted to bipartitions (when probability = FALSE) in predict function? I thought it is using some fixed threshold (e.g. 0.5) but my results show it is not the case. Would you please help me figure out how probabilities and bipartitions are computed?

Many thanks in advance,
Seda

**Comment by rivolli** [comment]
Hi Seda, I'm glad you liked it.

About your question, in fact, the prediction function uses the values from the base model directly.
I suppose the differences you have been observed is due to the empty prediction, which is avoided by default.

Please, before uses the prediction function set 
`options(utiml.empty.prediction=TRUE)`

I believe that you will not have the differences anymore.
More details you can also find in our paper https://journal.r-project.org/archive/2018/RJ-2018-041/index.html

Also, please, let me know if it works.
Thank you.

**Comment by SedaArat** [comment]
Hi Adriano,

Thank you for your response and the link for your paper. They are so helpful.

And yes, I don’t have the discrepancy anymore. Setting the options(utiml.empty.prediction=TRUE) helped a lot!

Also, would you please let me know how to cite your work? Was it already published in a journal or should I cite it as a link you provided: https://journal.r-project.org/archive/2018/RJ-2018-041/index.html ?

All the best,
Seda

Seda Arat, Ph.D.
Data Scientist | Carter Lab | B400 3115.03
The Jackson Laboratory 
Farmington, CT 06032
267-752-2739
seda8arat@gmail.com

**Comment by rivolli** [comment]
The paper was accepted but not published yet, so you can cite as: Rivolli
A,  de  Carvalho  ACPLF  (2018)  The  utiml  Package:  Multi-label
Classification  inR.  The  R  Journal  URL
https://journal.r-project.org/archive/2018/RJ-2018-041/index.html

Or using the bibtex

@article{RJ-2018-041,
  author = {Adriano Rivolli and Andre C. P. L. F. de Carvalho},
  title = {{The utiml Package: Multi-label Classification in R}},
  year = {2018},
  journal = {{The R Journal}},
  url = {https://journal.r-project.org/archive/2018/RJ-2018-041/index.html}
}

Thank you so much.
Any questions please let me know.

Cheers,
Adriano Rívolli da Silva
